### ISSUE TITLE
puv and nvs profiles

### ISSUE THREAD

**Issue by alko-k** [surroundaustralia/VocPrez-theme-nvs#90]
Ensure that the RDF/XML and html for the NVS profile only includes skos:broader, narrower, sameAs and related properties as mappings.
Enable a new profile, the puv profile to include all elements from the puv ontology here: https://github.com/CSIRO-enviro-informatics/PUV-ont/blob/main/rdf/puv.ttl
The additional properties will appear in the following vocabularies:
A05
P01 
S02     BODC parameter semantic model relationships between what theme and where theme
S03     BODC parameter semantic model sample preparation entity descriptions
S04     BODC parameter semantic model analytical method entity descriptions
S05     BODC parameter semantic model data processing entity descriptions
S06     BODC parameter semantic model parameter entity names
S07     BODC parameter semantic model parameter statistic
S09     BODC parameter semantic model biological entity size terms
S10     BODC parameter semantic model biological entity sex category terms
S11     BODC parameter semantic model biological entity development stage terms
S12     BODC parameter semantic model biological entity subcomponent terms
S13     BODC parameter semantic model biological entity subgroup terms
S14     BODC parameter semantic model biological entity morphology terms
S15     BODC parameter semantic model biological entity colour terms
S18     BODC parameter semantic model physical entity names
S19     BODC parameter semantic model physical entity subgroup names
S20     BODC parameter semantic model physical entity datum names
S21     BODC parameter semantic model sphere names
S22     BODC parameter semantic model sphere subgroup names
S23     BODC semantic model sphere phase names
S24     BODC semantic model sphere phase subgroup names
S25     BODC parameter semantic model biological entity names
S26     BODC parameter semantic model matrices
S27     BODC parameter semantic model chemical substances
S29     BODC parameter semantic model physical entity compound names
S30     BODC parameter semantic model relationships between biological entities

**Comment by nicholascar** [comment]
Non-PUV vocabs render as before:

http://nvs.surroundaustralia.com/collection/R19/current/

PUV vocabs render with an additional statement "This collection is part of the Parameter Usage Vocabulary set of vocabularies.":

http://nvs.surroundaustralia.com/collection/S02/current/

Non-PUV Concepts render as before:

http://nvs.surroundaustralia.com/collection/R19/current/1/

PUV Concepts also default render as before, since the NVS view is unchanged:

http://nvs.surroundaustralia.com/collection/S02/current/S021/

However, PUV Concepts list another alternate view, "puv":

http://nvs.surroundaustralia.com/collection/S02/current/S021/?_profile=alt

The PUV HTML view lists PUV properties as well as NVS properties:

http://nvs.surroundaustralia.com/collection/S02/current/S021/?_profile=puv&_mediatype=text/html

The PUV RDF lists PUV properties as well as NVS properties:

http://nvs.surroundaustralia.com/collection/S02/current/S021/?_profile=puv&_mediatype=text/turtle


_I have used static, dummy, PUV data for all PUV Concepts for now since the triplestore doesn't contain any real data but created this task to remedy that: Issue #91_
